/** Siglas que devem permanecer em maiúsculas, mesmo se vierem usp / Usp. */
export const ACRONYM_DISPLAY: Record<string, string> = {
  anvisa: "ANVISA",
  capes: "CAPES",
  cederj: "CEDERJ",
  cefet: "CEFET",
  cnpq: "CNPq",
  embrapa: "Embrapa",
  ensp: "ENSP",
  fapemig: "FAPEMIG",
  faperj: "FAPERJ",
  fapesp: "FAPESP",
  fgv: "FGV",
  finep: "FINEP",
  fiocruz: "Fiocruz",
  furb: "FURB",
  furg: "FURG",
  ibge: "IBGE",
  ibict: "IBICT",
  ies: "IES",
  ifba: "IFBA",
  ifce: "IFCE",
  ifes: "IFES",
  iff: "IFF",
  ifgo: "IFGO",
  ifma: "IFMA",
  ifmg: "IFMG",
  ifpa: "IFPA",
  ifpb: "IFPB",
  ifpe: "IFPE",
  ifpi: "IFPI",
  ifpr: "IFPR",
  ifrj: "IFRJ",
  ifrn: "IFRN",
  ifrs: "IFRS",
  ifsc: "IFSC",
  ifsp: "IFSP",
  impa: "IMPA",
  inmetro: "INMETRO",
  inpa: "INPA",
  inpe: "INPE",
  ipea: "IPEA",
  isbn: "ISBN",
  issn: "ISSN",
  ita: "ITA",
  mcti: "MCTI",
  mec: "MEC",
  orcid: "ORCID",
  puc: "PUC",
  pusp: "PUSP",
  scielo: "SciELO",
  senac: "SENAC",
  senai: "SENAI",
  sesc: "SESC",
  sesi: "SESI",
  ucb: "UCB",
  udesc: "UDESC",
  uece: "UECE",
  uefs: "UEFS",
  ueg: "UEG",
  uel: "UEL",
  uem: "UEM",
  uema: "UEMA",
  uemg: "UEMG",
  uems: "UEMS",
  uenf: "UENF",
  uepg: "UEPG",
  uerj: "UERJ",
  uesb: "UESB",
  uesc: "UESC",
  uespi: "UESPI",
  ufabc: "UFABC",
  ufac: "UFAC",
  ufam: "UFAM",
  ufba: "UFBA",
  ufc: "UFC",
  ufca: "UFCA",
  ufes: "UFES",
  uff: "UFF",
  ufg: "UFG",
  ufjf: "UFJF",
  ufla: "UFLA",
  ufma: "UFMA",
  ufmg: "UFMG",
  ufms: "UFMS",
  ufmt: "UFMT",
  ufob: "UFOB",
  ufop: "UFOP",
  ufpa: "UFPA",
  ufpb: "UFPB",
  ufpe: "UFPE",
  ufpi: "UFPI",
  ufpr: "UFPR",
  ufrb: "UFRB",
  ufrgs: "UFRGS",
  ufrj: "UFRJ",
  ufrn: "UFRN",
  ufrr: "UFRR",
  ufs: "UFS",
  ufsb: "UFSB",
  ufsc: "UFSC",
  ufscar: "UFSCar",
  ufsj: "UFSJ",
  uft: "UFT",
  uftm: "UFTM",
  ufu: "UFU",
  ufv: "UFV",
  ufvjm: "UFVJM",
  ulbra: "ULBRA",
  unb: "UnB",
  unemat: "UNEMAT",
  unesp: "UNESP",
  unicamp: "UNICAMP",
  unifal: "UNIFAL",
  unifap: "UNIFAP",
  unifei: "UNIFEI",
  unifesp: "UNIFESP",
  unila: "UNILA",
  unilab: "UNILAB",
  unipampa: "UNIPAMPA",
  unir: "UNIR",
  unirio: "UNIRIO",
  univasf: "UNIVASF",
  upe: "UPE",
  upf: "UPF",
  usp: "USP",
  utfpr: "UTFPR",
};

export function formatAcronym(word: string): string | null {
  const mapped = ACRONYM_DISPLAY[word.toLowerCase()];
  if (mapped) return mapped;

  if (
    word.length >= 3 &&
    word.length <= 6 &&
    word === word.toUpperCase() &&
    /^[A-ZÁÀÂÃÉÊÍÓÔÕÚÇ]+$/.test(word)
  ) {
    return word;
  }

  return null;
}
